# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94fe0ac0dc7566ce024ad0639676a5bf91fe11ab28cdd5da31c81ec2568f6e43308739452d4b1aa8403d17c5c56c31e8848a2294c23ee290b33bb8cb75cadeb1

test:
  secret_key_base: c188f7380eaadc47504afeb751b57740f5e9677482622b9b9bacbd4c6e7e59d4f00971a095217d15dc40ca61c2e2b271fa6af42e0a867bacfa5e786678cc1aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
